language: go
services:
  - rabbitmq
env:
  - AMQP_URI=amqp://guest:guest@localhost:5672/
go:
  - 1.3
  - 1.4
  - tip
install:
  - go get github.com/codegangsta/cli
  - go get github.com/streadway/amqp
script:
  - go install
  - seq 1 10 | pipecat publish numbers
  - pipecat consume numbers --autoack | xargs -n 1 expr 10 '*' | pipecat publish results
  - pipecat consume results --autoack --non-blocking
